// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef SEMINDEX_PATHS_H
#define SEMINDEX_PATHS_H

#define SEMINDEX_STATE_DIRECTORY ".semindex"
#define SEMINDEX_SYMBOL_DATABASE "semindex.db"
#define SEMINDEX_COMMAND_DATABASE "commands.db"

#define SEMINDEX_DEFAULT_SYMBOL_DATABASE SEMINDEX_STATE_DIRECTORY "/" SEMINDEX_SYMBOL_DATABASE
#define SEMINDEX_DEFAULT_COMMAND_DATABASE SEMINDEX_STATE_DIRECTORY "/" SEMINDEX_COMMAND_DATABASE

#endif /* SEMINDEX_PATHS_H */
